#############################################################################
# Makefile for building: iup
# Generated by qmake (2.01a) (Qt 4.3.0) on: Tue Jul 3 12:10:35 2007
# Project:  iup.pro
# Template: subdirs
# Command: /opt/qt4/bin/qmake -unix -o Makefile iup.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /opt/qt4/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-iup \
		sub-iupcontrols \
		sub-cd \
		sub-examples

iup//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) iup/ || $(MKDIR) iup/ 
	cd iup/ && $(QMAKE) iup.pro -unix -o $(MAKEFILE)
sub-iup-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) iup/ || $(MKDIR) iup/ 
	cd iup/ && $(QMAKE) iup.pro -unix -o $(MAKEFILE)
sub-iup: iup//$(MAKEFILE) FORCE
	cd iup/ && $(MAKE) -f $(MAKEFILE)
sub-iup-make_default: iup//$(MAKEFILE) FORCE
	cd iup/ && $(MAKE) -f $(MAKEFILE) 
sub-iup-make_first: iup//$(MAKEFILE) FORCE
	cd iup/ && $(MAKE) -f $(MAKEFILE) first
sub-iup-all: iup//$(MAKEFILE) FORCE
	cd iup/ && $(MAKE) -f $(MAKEFILE) all
sub-iup-clean: iup//$(MAKEFILE) FORCE
	cd iup/ && $(MAKE) -f $(MAKEFILE) clean
sub-iup-distclean: iup//$(MAKEFILE) FORCE
	cd iup/ && $(MAKE) -f $(MAKEFILE) distclean
sub-iup-install_subtargets: iup//$(MAKEFILE) FORCE
	cd iup/ && $(MAKE) -f $(MAKEFILE) install
sub-iup-uninstall_subtargets: iup//$(MAKEFILE) FORCE
	cd iup/ && $(MAKE) -f $(MAKEFILE) uninstall
iupcontrols//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) iupcontrols/ || $(MKDIR) iupcontrols/ 
	cd iupcontrols/ && $(QMAKE) iupcontrols.pro -unix -o $(MAKEFILE)
sub-iupcontrols-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) iupcontrols/ || $(MKDIR) iupcontrols/ 
	cd iupcontrols/ && $(QMAKE) iupcontrols.pro -unix -o $(MAKEFILE)
sub-iupcontrols: iupcontrols//$(MAKEFILE) FORCE
	cd iupcontrols/ && $(MAKE) -f $(MAKEFILE)
sub-iupcontrols-make_default: iupcontrols//$(MAKEFILE) FORCE
	cd iupcontrols/ && $(MAKE) -f $(MAKEFILE) 
sub-iupcontrols-make_first: iupcontrols//$(MAKEFILE) FORCE
	cd iupcontrols/ && $(MAKE) -f $(MAKEFILE) first
sub-iupcontrols-all: iupcontrols//$(MAKEFILE) FORCE
	cd iupcontrols/ && $(MAKE) -f $(MAKEFILE) all
sub-iupcontrols-clean: iupcontrols//$(MAKEFILE) FORCE
	cd iupcontrols/ && $(MAKE) -f $(MAKEFILE) clean
sub-iupcontrols-distclean: iupcontrols//$(MAKEFILE) FORCE
	cd iupcontrols/ && $(MAKE) -f $(MAKEFILE) distclean
sub-iupcontrols-install_subtargets: iupcontrols//$(MAKEFILE) FORCE
	cd iupcontrols/ && $(MAKE) -f $(MAKEFILE) install
sub-iupcontrols-uninstall_subtargets: iupcontrols//$(MAKEFILE) FORCE
	cd iupcontrols/ && $(MAKE) -f $(MAKEFILE) uninstall
cd//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) cd/ || $(MKDIR) cd/ 
	cd cd/ && $(QMAKE) cd.pro -unix -o $(MAKEFILE)
sub-cd-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) cd/ || $(MKDIR) cd/ 
	cd cd/ && $(QMAKE) cd.pro -unix -o $(MAKEFILE)
sub-cd: cd//$(MAKEFILE) FORCE
	cd cd/ && $(MAKE) -f $(MAKEFILE)
sub-cd-make_default: cd//$(MAKEFILE) FORCE
	cd cd/ && $(MAKE) -f $(MAKEFILE) 
sub-cd-make_first: cd//$(MAKEFILE) FORCE
	cd cd/ && $(MAKE) -f $(MAKEFILE) first
sub-cd-all: cd//$(MAKEFILE) FORCE
	cd cd/ && $(MAKE) -f $(MAKEFILE) all
sub-cd-clean: cd//$(MAKEFILE) FORCE
	cd cd/ && $(MAKE) -f $(MAKEFILE) clean
sub-cd-distclean: cd//$(MAKEFILE) FORCE
	cd cd/ && $(MAKE) -f $(MAKEFILE) distclean
sub-cd-install_subtargets: cd//$(MAKEFILE) FORCE
	cd cd/ && $(MAKE) -f $(MAKEFILE) install
sub-cd-uninstall_subtargets: cd//$(MAKEFILE) FORCE
	cd cd/ && $(MAKE) -f $(MAKEFILE) uninstall
examples//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) examples/ || $(MKDIR) examples/ 
	cd examples/ && $(QMAKE) examples.pro -unix -o $(MAKEFILE)
sub-examples-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) examples/ || $(MKDIR) examples/ 
	cd examples/ && $(QMAKE) examples.pro -unix -o $(MAKEFILE)
sub-examples: examples//$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE)
sub-examples-make_default: examples//$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) 
sub-examples-make_first: examples//$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) first
sub-examples-all: examples//$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) all
sub-examples-clean: examples//$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) clean
sub-examples-distclean: examples//$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) distclean
sub-examples-install_subtargets: examples//$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) install
sub-examples-uninstall_subtargets: examples//$(MAKEFILE) FORCE
	cd examples/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: iup.pro  /opt/qt4/mkspecs/linux-g++/qmake.conf /opt/qt4/mkspecs/common/g++.conf \
		/opt/qt4/mkspecs/common/unix.conf \
		/opt/qt4/mkspecs/common/linux.conf \
		/opt/qt4/mkspecs/qconfig.pri \
		/opt/qt4/mkspecs/features/qt_functions.prf \
		/opt/qt4/mkspecs/features/qt_config.prf \
		/opt/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/qt4/mkspecs/features/default_pre.prf \
		/opt/qt4/mkspecs/features/release.prf \
		/opt/qt4/mkspecs/features/default_post.prf \
		/opt/qt4/mkspecs/features/warn_on.prf \
		/opt/qt4/mkspecs/features/qt.prf \
		/opt/qt4/mkspecs/features/unix/thread.prf \
		/opt/qt4/mkspecs/features/moc.prf \
		/opt/qt4/mkspecs/features/resources.prf \
		/opt/qt4/mkspecs/features/uic.prf \
		/opt/qt4/mkspecs/features/yacc.prf \
		/opt/qt4/mkspecs/features/lex.prf
	$(QMAKE) -unix -o Makefile iup.pro
/opt/qt4/mkspecs/common/g++.conf:
/opt/qt4/mkspecs/common/unix.conf:
/opt/qt4/mkspecs/common/linux.conf:
/opt/qt4/mkspecs/qconfig.pri:
/opt/qt4/mkspecs/features/qt_functions.prf:
/opt/qt4/mkspecs/features/qt_config.prf:
/opt/qt4/mkspecs/features/exclusive_builds.prf:
/opt/qt4/mkspecs/features/default_pre.prf:
/opt/qt4/mkspecs/features/release.prf:
/opt/qt4/mkspecs/features/default_post.prf:
/opt/qt4/mkspecs/features/warn_on.prf:
/opt/qt4/mkspecs/features/qt.prf:
/opt/qt4/mkspecs/features/unix/thread.prf:
/opt/qt4/mkspecs/features/moc.prf:
/opt/qt4/mkspecs/features/resources.prf:
/opt/qt4/mkspecs/features/uic.prf:
/opt/qt4/mkspecs/features/yacc.prf:
/opt/qt4/mkspecs/features/lex.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -unix -o Makefile iup.pro

qmake_all: sub-iup-qmake_all sub-iupcontrols-qmake_all sub-cd-qmake_all sub-examples-qmake_all FORCE

make_default: sub-iup-make_default sub-iupcontrols-make_default sub-cd-make_default sub-examples-make_default FORCE
make_first: sub-iup-make_first sub-iupcontrols-make_first sub-cd-make_first sub-examples-make_first FORCE
all: sub-iup-all sub-iupcontrols-all sub-cd-all sub-examples-all FORCE
clean: sub-iup-clean sub-iupcontrols-clean sub-cd-clean sub-examples-clean FORCE
distclean: sub-iup-distclean sub-iupcontrols-distclean sub-cd-distclean sub-examples-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-iup-install_subtargets sub-iupcontrols-install_subtargets sub-cd-install_subtargets sub-examples-install_subtargets FORCE
uninstall_subtargets: sub-iup-uninstall_subtargets sub-iupcontrols-uninstall_subtargets sub-cd-uninstall_subtargets sub-examples-uninstall_subtargets FORCE

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

