warning( "This file has been generated by Monkey Studio (2006.1.6.0) - http://sourceforge.net/projects/monkeystudio" )

AUTHOR	= Roberto Alsina
TEMPLATE	= lib
EMAIL	= ralsina@kde.org
win32:INCLUDEPATH	+= ../include ../../include ../cd ../../iup
unix:INCLUDEPATH	+= ../include ../../include ../cd ../../iup
CONFIG	+= lib qt
DESTDIR	= ../../lib/

win32:SOURCES	+= cdwiup.c

unix:SOURCES	+= cdqtiup.cpp

