int do_vdcext ( tpoint, tpoint );
int do_bckcol ( trgb );
int do_transp ( int );
int do_clprec ( tpoint, tpoint );
int do_clpind ( int );
int do_polyln ( int, tpoint * );
int do_incply ( int, tpoint * );
int do_djtply ( int, tpoint * );
int do_indpl ( int, tpoint * );
int do_polymk ( int, tpoint * );
int do_incplm ( int, tpoint * );
int do_text ( int, char *, tpoint );
int do_txtalign ( int hor, int ver );
int do_polygn ( int, tpoint * );
int do_incplg ( int, tpoint * );
int do_plgset( int, int, tpoint *, short * );
int do_cellar ( tpoint, tpoint, tpoint, int, int, long, tcolor * );
int do_gdp ( int, tpoint *, char * );
int do_rect ( tpoint point1, tpoint point2 );
int do_circle ( tpoint, double );
int do_circ3p ( tpoint, tpoint, tpoint );
int do_circ3pc ( tpoint, tpoint, tpoint, int );
int do_circcnt ( tpoint, tpoint, tpoint, double );
int do_ccntcl ( tpoint, tpoint, tpoint, double, int );
int do_ellips ( tpoint, tpoint, tpoint );
int do_ellarc ( tpoint, tpoint, tpoint, tpoint, tpoint );
int do_ellacl ( tpoint, tpoint, tpoint, tpoint, tpoint, int );
int do_text_height ( double );
